- hosts: localhost
  name: "ONTAP Health: Node State"
  vars:
    hostname: 10.128.113.70
    username: admin
    password: Netapp01
  tasks:
  - uri: url="https://{{ hostname }}/api/cluster/nodes" url_username="{{ username }}" url_password="{{ password }}"
         method=GET validate_certs=no force_basic_auth=yes use_proxy=no
    register: nodes_ids
  - uri: url="https://{{ hostname }}/api/cluster/nodes/{{ item.uuid }}" url_username="{{ username}}" url_password="{{ password }}"
         method=GET validate_certs=no force_basic_auth=yes use_proxy=no
    loop: "{{ nodes_ids.json.records }}"
    register: nodes_details
  - assert:
      that: item.json.state == "up"
      fail_msg: "node {{ item.json.name }} is down"
      quiet: true
    loop: "{{ nodes_details.results }}"
    any_errors_fatal: no
  - assert:
      that: item.json.service_processor.state == "online"
      fail_msg: "node {{ item.json.name }} service processor is offline"
      quiet: true
    loop: "{{ nodes_details.results }}"
    any_errors_fatal: no
